### ISSUE TITLE
Some errors, when building Xcode9

### ISSUE THREAD

**Issue by onthehand** [fotiDim/Romo#1]
I have some questions to build the project "Romo".

(1) Location of RMShare
Should RMShare directory be under "Romo" directory, not under SDK?

(2) RMShare/DDLog.h ?
I got the following error.
"RMShare/DDLog.h file not found".

Should it be "#include CocoaLumberjack/DDLog.h"?

However, even if I changed the line, other errors occur.
So, I have not succeeded to build the project yet.

(3) bitcode
OpenCV2 framework does not contain bitcode.
So, I have to disable bitcode option.
Should I build OpenCV2 from source code?

My environment is the following.
 - Xocde 9.0
 - iOS 11.0

Thanks.

**Comment by fotiDim** [comment]
Hi there, answers below:
(1) The folder structure is intact for now. I inherited it from the old project. Yes some cleanups and restructuring needs to be done.
(2) The *Romo* project is not fixed yet. Try the *sample code* folder for now.
(3) If you download a new version of the framework it comes with bitcode support.
