### ISSUE TITLE
How far are we from a working ipa

### ISSUE THREAD

**Issue by Jinkxt** [fotiDim/Romo#11]
Hello, 
I'm a new member to the romo community, i actually just bought a romo (lightning) today, to my surprise i plugged in my iphone 5 to find out that the app doesn't exist on the appstore anymore.
the only meaningful  result i  got after a long research online was this thread on github.
sadly i don't know much about Xcode (i wish i did).
looking only for basic functions the ROMO app used to have (example on youtube) was wondering if any has compiled such a thing for  the later IOSs or has some sort of a work  around just to  get  the robot to start, even without the remote control functions.
Thank you in advance for any comments  of the  subject (and sorry if this is the wrong place to publish  such a thing)

**Comment by fotiDim** [comment]
Hi Jinkxt,
thank you for your message. I totally get your concern. The app is not far.
I am waiting for iOS 12 GM to test things out and I will release when iOS
12 stable is out.

What kind of phone do you use?

**Comment by Jinkxt** [comment]
Hey,
Thank u for the fast reply , this is wonderful news , this is the only hope for my romo to breath again.
My phone is : iphone 5 ( not 5s)
And I'm currently on ios 10.3.3

**Comment by fotiDim** [comment]
The app is there! Find the *Romo X* app on the [App Store](https://itunes.apple.com/us/app/romo-x/id1436292886)
