### ISSUE TITLE
iPhone 4S support

### ISSUE THREAD

**Issue by Suschman** [fotiDim/Romo#12]
Hi,

Fresh updated and reset Iphone 4s, Ios 9.3.5. App cannot install ("Not compatible with this iphone").
I think app it is set to require 11+, not 8+ releases. Please have a look.
Thanks for the release and your work anyway :+1: 

Will try it with a 5s later (have Romo3 and Romo3L avaliable).

**Comment by fotiDim** [comment]
@Suschman update coming up. It will make the app compatible with 4S. I will ping you when it is live.

**Comment by Suschman** [comment]
wow, thats some quick turnaround time :)
Thanks.

**Comment by fotiDim** [comment]
@Suschman keep in mind you are the first one to try it. I have no 30pin Romo so I after the update is live I am expecting you to report back your results.

**Comment by Suschman** [comment]
@fotiDim i suppose app update is not finished?
I see romo x 1,0 on the 4s but still complains about needs ios11.
Iphone 5s ios12 works ❤

**Comment by fotiDim** [comment]
No, not yet. We are waiting for App Store approval. It should come out as
version 1.1 in a couple of days.

**Comment by fotiDim** [comment]
@Suschman update 1.1 is out. Please test it with your 4S!

**Comment by Suschman** [comment]
Going trough the intro now, App works and robot base as well.

**Comment by fotiDim** [comment]
Sounds good then. Seems to be working fine!

**Comment by fotiDim** [comment]
Closing down the issue since compatibility with 4S is restored. If you find an issue feel free to reopen.

**Comment by fotiDim** [comment]
@Suschman which Romo device version do you have? Is it Romo3A (white box)?

**Comment by Suschman** [comment]
Not sure what your referring to exactly. Romo3 and 3L i have came both in same blueish box design, only difference the 4S / 5 remarks. Do you have some photo reference?

**Comment by fotiDim** [comment]
It is this [version](https://www.youtube.com/watch?v=t-4ejDZn504). Do we have any idea what the difference is?

**Comment by Suschman** [comment]
Ok, its actually Romo3B. Never noticed.
Cannot see a difference from the video to the Romo besides way different box artwork and lettering.
Maybe 3B is a respin with the 3L release. 3A Looks like the first production run.
Does the code actually check any fw version inside romo or can push an update to the embedded avr?

**Comment by fotiDim** [comment]
Let's continue [here](https://github.com/fotiDim/Romo/issues/14).
