### ISSUE TITLE
Errors on building RMVision for simulators

### ISSUE THREAD

**Issue by timiswq** [fotiDim/Romo#2]
I have already move opencv2.frameworks to lib folder, but still errors shown as 
 
![image](https://user-images.githubusercontent.com/11385070/36932840-7557fa70-1f0a-11e8-8bf6-1440fe926032.png)
and this is my project

![wx20180303-174708](https://user-images.githubusercontent.com/11385070/36932875-f0435676-1f0a-11e8-94a0-1a9d32f8ad14.png)

**Comment by fotiDim** [comment]
This is a known issue. libjpeg is the problem. If you see the Readme it mentions "Refactor RMVision (Partially done. Need to recompile libjpeg fat binary for all architectures. Now it cannot run on simulators)" as not done.

If you try to compile for a device it will work. For If you have any ideas on how to get a proper build of libjpeg feel free to file a pull request.

**Comment by fotiDim** [comment]
@timiswq the issue is resolved now. Pull from the repo and you should be good to go.

**Comment by timiswq** [comment]
Thank u very much! It seems worked now.
