### ISSUE TITLE
In correct repository path

### ISSUE THREAD

**Issue by hisabonbon** [fotiDim/Romo#21]
I appreciate your grateful repository.

When I tried "pod install" with "pod Romo", it failed due to repository not found.
`/usr/bin/git clone https://github.com/navideck/Romo /var/folders/dn/94wbjr_s19x_l2h60d_pr3_w0000gp/T/d20210313-97211-4nrfri --template= --single-branch --depth 1 --branch Romo_v0.5.1`

I think /navideck/Romo is a repository for Romo application, but it should cone Romo-iOS-SDK.
I guess it should be "/navideck/Romo-iOS-SDK".

**Comment by fotiDim** [comment]
Hi @hisabonbon. You are right! The repo was renamed recently and the pod was not updated. I just published 0.5.2. Can you please run `pod update` and let me know if it works for you?

**Comment by hisabonbon** [comment]
Wooowwww!!!! It works.
My Romo has relived!!
Fantastic!

Deeply thanks a lot!

**Comment by fotiDim** [comment]
Great! Have fun with Romo and make sure to share it if you build anything cool!
