### ISSUE TITLE
Trouble using SDK

### ISSUE THREAD

**Issue by markbresler** [fotiDim/Romo#25]
Foti,
I have continued to try and use the SDK. I am using a M1 MacBook Air running macOS 13.2.1 (22D68). I am using Xcode version 14.2. I am using an iPod running iOS 15.7.3 and have been able to add 'Romo' to the podfile but not 'Romo/RMCharacter'
or 'Romo/RMVision'. Below is my trial with Romo and Romo/RMCharacter. First the podfile, then a screenshot of the error messages.
—————
# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Mark-Romo-Test13' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Mark-Romo-Test13
  pod 'Romo'
  pod 'Romo/RMCharacter'
  # pod 'Romo/RMVision'

workspace 'Mark-test-13'

end
------
￼
Thanks So much for looking into this, Mark

**Comment by fotiDim** [comment]
@markbresler I am not sure what kind of error you got exactly. I gave it a try and only got a potential issue with RMCharacter. I have updated the readme with improved instructions. You can use the sample `Podfile` after changing the app name in the Podfile. Let me know if that solves your issue.
