### ISSUE TITLE
Thanks for maintaining this repo!

### ISSUE THREAD

**Issue by cnnn** [fotiDim/Romo#3]
I’m a Romo user and fan. Glad to see you actively maintaining this repo and made significant progress. I’m also interested in bringing my Romo back to life and continue developing on it.

I got the main app and Romo Control compiled on Xcode 9 for arm64, after removing some func calls to OpenTok framework and AVCEncoder library. Although I’m still struggling with socket issue between Romo and Romo Control, I can submit a PR with what I got so far.

**Comment by fotiDim** [comment]
@cnnn glad that you find it useful. If your changes are too many consider submitting multiple PRs to break things down and to be easier to review.

What kind of socket issue do you face?

**Comment by cnnn** [comment]
@fotiDim I figured it was due to IPv6 address. I'm now forcing to IPv4 address and the socket sendto issue is gone. Now Romo Control and Romo can communicate.

I'm trying to fix some font issue in RMVoice, then I'll move to getting video working. I wonder if you happen to have found AVCEncoder source code to compile for arm64?

**Comment by fotiDim** [comment]
No didn't dig into this yet. See what you can do and if you don't figure it out then open an issue so either me or somebody else looks into this.

**Comment by fotiDim** [comment]
@cnnn a quick search led me [here](https://github.com/kewlbear/FFmpeg-iOS-build-script)

**Comment by musicbravo** [comment]
I am so happy that you are looking at this. I work in a school that bought a batch load of ROMOs about 4 years ago and we updated out ipad minis to ios11, losing remote functionality. Will you be releasing a new build on the app store if you get everything working?

**Comment by cnnn** [comment]
@fotiDim I got most of static lib in libav recompiled for arm64 thanks to that repo, but AVCEncoder isn't part of it. Couldn't find anything or GitHub and that leads me to believe the source code is lost unless we can reach to the author whose name is in the header. That seems leaves us only one option, to replace it with some modern library.

**Comment by musicbravo** [comment]
I don't know if this helps you, but the person who used to give me the betas for this app when it last broke was a man called Tony Rushforth who worked with the developers of the apps when Osborne Technologies were marketing it.

**Comment by cnnn** [comment]
@musicbravo I do not have plan to put the apps on App Store, but you should be free to use the code and deploy to the school devices.

**Comment by fotiDim** [comment]
@musicbravo My short term plan for is to complete the SDK. An App Store app could come later. Please consider supporting the project on [Patreon](https://www.patreon.com/posts/help-bring-romo-17399481) and spreading the word about it.
I will try to get in touch with your suggested contact to see if he can help us with it.

@cnnn I opened an new issue for AVCEncoder. Let's move the conversation [there](https://github.com/fotiDim/Romo/issues/4).

**Comment by musicbravo** [comment]
I certainly will consider becoming a patron. In the mean time i have an *.ipa file from 2016 for the main romo app. Is there anything you can do with this?

**Comment by fotiDim** [comment]
@musicbravo can you please upload it somewhere and provide the link?

**Comment by musicbravo** [comment]
Yes I can. But it will be after the weekend as it is on my work mac



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by cnnn** [comment]
The PR is available here https://github.com/fotiDim/Romo/pull/5 with video working fine.

Tested with an iPhone SE as host, and iPhone 8 Plus as Remote. Both running iOS 11.

**Comment by musicbravo** [comment]
Great stuff.

I will try it out when I get back to work



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by musicbravo** [comment]
@fotiDim Here is a link to that IPA file
https://dallimoreprimaryschool-my.sharepoint.com/:f:/g/personal/edwards_c53_dallimore_derbyshire_sch_uk/Egp2AlKHX9xFg28vlM7-JhYBhYqFlE_YA5hM7Jq5GupENQ

**Comment by fotiDim** [comment]
Since we have an app now I am closing this issue. Whoever wants to support development can buy the  *Romo X* app on the [App Store](https://itunes.apple.com/us/app/romo-x/id1436292886).

Thank you for your support!

**Comment by fotiDim** [comment]
@musicbravo can you upload the IPA again? The link seems to have expired.

**Comment by musicbravo** [comment]
Yes I will try to do it today



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by musicbravo** [comment]
[https://dallimoreprimaryschool-my.sharepoint.com/:f:/g/personal/edwards_c53_dallimore_derbyshire_sch_uk/Egp2AlKHX9xFg28vlM7-JhYBhYqFlE_YA5hM7Jq5GupENQ?e=nxa0vv]
The link will be open until the end of the month. Did you say there is a fully working app now?

**Comment by musicbravo** [comment]
[https://dallimoreprimaryschool-my.sharepoint.com/:f:/g/personal/edwards_c53_dallimore_derbyshire_sch_uk/Egp2AlKHX9xFg28vlM7-JhYBhYqFlE_YA5hM7Jq5GupENQ?e=nxa0vv](url)
The link will be open till the end of the month. Did you say there is an app now?

**Comment by fotiDim** [comment]
@musicbravo thank you. Yep, app is not the App Store. Search for `Romo X`.
