### ISSUE TITLE
Compile AVCEncoder for arm64

### ISSUE THREAD

**Issue by fotiDim** [fotiDim/Romo#4]
So far it was not possible to find the source code or compiled binaries of AVCEncoder for arm64.

- We can either search more hoping that we will find something
- Replace AVEncoder with another library

**Comment by cnnn** [comment]
The best replacement seems to be hardware accelerated H264 encoder/decoder with VideoToolbox.

**Comment by fotiDim** [comment]
Yep, I would go with native iOS APIs as well. In fact I plan to do that for the rest of the current dependencies as well.

**Comment by cnnn** [comment]
This isn't required anymore with https://github.com/fotiDim/Romo/pull/5
